version: '3'
services:
  stock-mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: stock_exchange
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - app-network

  stock-app:
    image: raphau/stock-exchange-backend:latest
    volumes:
      - ./stockExchange:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - stock-mysql
    networks:
      - app-network

  traffic-mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: traffic_generator
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3307"
    networks:
      - app-network

  traffic-app:
    image: raphau/traffic-generator-backend
    volumes:
      - ./traffic-generator:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - "8081:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - traffic-mysql
    networks:
      - app-network
    
  stock-front:
    image: raphau/stock-front:latest
    ports:
      - "8083:80"
    networks:
      - app-network
      
networks:
  app-network:
    external: true