version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - ~/.docker/rabbitmq/etc/:/etc/rabbitmq/
    #   - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker/rabbitmq/logs/:/var/log/rabbitmq/
    networks:
      - app-network

  stock-mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: stock_exchange
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    command: "--max_connections=10000"
    ports:
      - "3306:3306"
    networks:
      - app-network

  stock-app:
    image: raphau/stock-exchange-backend:latest
    volumes:
      - ./stockExchange:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - stock-mysql
      - rabbitmq
    networks:
      - app-network

  traffic-mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: traffic_generator
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    networks:
      - app-network

  traffic-app:
    image: raphau/traffic-generator-backend:latest
    volumes:
      - ./traffic-generator:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    environment:
        - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8081"
    command: mvn clean spring-boot:run
    depends_on:
      - traffic-mysql
      - rabbitmq
    networks:
      - app-network
    
  # stock-front:
  #   image: raphau/stock-front:latest
  #   ports:
  #     - "8083:80"
  #   networks:
  #     - app-network
      
networks:
  app-network:
    external: true